# Generated by Django 3.2.5 on 2021-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=200, verbose_name='Nombre y Apellido Cliente')),
                ('tipo_banco', models.CharField(choices=[('PRIVADO', 'PRIVADO'), ('GOBIERNO', 'GOBIERNO')], max_length=100, verbose_name='Tipo Banco')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección de Banco')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
    ]
