# Generated by Django 3.2.5 on 2021-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nombre_banco',
            field=models.CharField(max_length=200, verbose_name='Nombre del Banco'),
        ),
    ]
