# Generated by Django 3.2.5 on 2021-07-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210722_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad del Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fec_nacimiento',
            field=models.DateField(max_length=2, verbose_name='Fecha de Nacimiento'),
        ),
    ]
