# Generated by Django 3.2.5 on 2021-07-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=200, verbose_name='Nombre y Apellido Cliente')),
                ('tipo_banco', models.CharField(choices=[('PRIVADO', 'PRIVADO'), ('GOBIERNO', 'GOBIERNO')], max_length=100, verbose_name='Tipo Banco')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección de Banco')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ape', models.CharField(max_length=250, verbose_name='Nombre y Apellido Cliente')),
                ('fec_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad del Cliente')),
                ('nacionalidad', models.CharField(choices=[('', 'SELECCIONE NACIONALIDAD'), ('E', 'EXTRANJERO'), ('V', 'VENEZOLANO')], max_length=200, verbose_name='Nacionalidad')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección de Habitación')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero Telefonico')),
                ('tipo_persona', models.CharField(choices=[('', 'SELECCIONE TIPO PERSONA'), ('NATURAL', 'NATURAL'), ('JÚRIDICO', 'JÚRIDICO')], max_length=200, verbose_name='Tipo Persona')),
                ('nombre_banco', models.CharField(choices=[('', 'SELECCIONE BANCO'), ('BANESCO', 'BANESCO'), ('VENEZUELA', 'VENEZUELA'), ('PROVINCIAL', 'PROVINCIAL')], max_length=200, verbose_name='Nombre del Banco')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_credito', models.CharField(max_length=200, verbose_name='Descripción del Credito')),
                ('pago_minimo', models.FloatField(verbose_name='Pago Minimo')),
                ('pago_maximo', models.FloatField(verbose_name='Pago Maximo')),
                ('plazo_credito', models.IntegerField(max_length=200, verbose_name='Plazo Credito')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('tipo_credito', models.CharField(choices=[('', 'SELECCIONE CREDITO'), ('AUTOMOTRIZ', 'AUTOMOTRIZ'), ('HIPOTECARIO', 'HIPOTECARIO'), ('COMERCIALES', 'COMERCIALES')], max_length=100, verbose_name='Tipo Credito')),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.banco')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.cliente')),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
            },
        ),
    ]
