# Generated by Django 3.2.5 on 2021-07-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210722_1656'),
        ('banco', '0002_alter_banco_nombre_banco'),
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='id_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.banco'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
