# Generated by Django 3.2.5 on 2021-07-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_alter_credito_plazo_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='pago_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credito',
            name='pago_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
