# Generated by Django 3.2.5 on 2021-07-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0004_auto_20210722_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='pago_maximo',
            field=models.FloatField(default=0, verbose_name='Pago Maximo'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='pago_minimo',
            field=models.FloatField(default=0, verbose_name='Pago Minimo'),
        ),
    ]
